# kitig-pvc.yaml，请求 PV 的存储资源
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-data-pvc
  namespace: kitig
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  