# Used to set configurations for the system

# Used to store uploaded files
temp_docs_path: "/root/.chatig/data/temp_docs"

# admin password
apikey:
  value: "chatig"

# main server port
port: 80

# database
database: "postgres://chatig:chatig@localhost/chatig"
connection_num: 10
# pgsql/mysql
database_type: "pgsql"

# kafaka
enabled: false
brokers: "x.x.x.x:9092"
topic: "ai_chatig_tokens"

# log level
log_level: info
