# Used to set configurations for the system

# Used to store uploaded files
temp_docs_path: "/root/.chatig/data/temp_docs"

# admin password
apikey:
  value: "chatig"

# main server port
port: 8001
server_cert_file: "/etc/chatig/https/server_cert_file.crt"
chain_cert_file: "/etc/chatig/https/chain_cert_file.crt"
key_file: "/etc/chatig/https/key_file.key"

# database
database: "postgres://chatig:chatig@localhost/chatig"
connection_num: 10
# pgsql/mysql
database_type: "pgsql"
# rate limit
rate_limit_enbled: false
rate_limit_tps: 1000
rate_limit_bucket_capacity: 2000
# refill/ms
rate_limit_refill_interval: 100
# auth
auth_local_enabled: false
auth_remote_enabled: false
auth_remote_server: ""
# cloud region
cloud_region_id: ""
cloud_region_name: ""

# coil server, such as ["192.168.56.6:8011", "192.168.56.7:8010"]
coil_enabled: false
multi_ip: []
connections_per_server: 32

# Log config
refresh_rate: 30 seconds

appenders:
  access_console:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  access_file:
    kind: rolling_file
    path: "/var/log/chatig/access.log"
    encoder:
      pattern: "{l} - {m}{n}"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 gb
      roller:
        kind: fixed_window
        pattern: "/var/log/chatig/access.{}.log"
        count: 5

  error_console:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  error_file:
    kind: rolling_file
    path: "/var/log/chatig/error.log"
    encoder:
      pattern: "{l} - {m}{n}"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 gb
      roller:
        kind: fixed_window
        pattern: "/var/log/chatig/error.{}.log"
        count: 5

  token_console:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  token_file:
    kind: rolling_file
    path: "/var/log/chatig/token.log"
    encoder:
      pattern: "{m}{n}"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 gb
      roller:
        kind: fixed_window
        pattern: "/var/log/chatig/token.{}.log"
        count: 2
        base: 1

loggers:
  token:
    level: info
    appenders:
      # - token_console
      - token_file
  access_log:
    level: info
    appenders:
      - access_console
      - access_file
  error_log:
    level: error
    appenders:
      - error_console
      - error_file
