# Used to set configurations for the system

# Used to store uploaded files
temp_docs_path: "/root/.chatig/data/temp_docs"

# apikey
apikey:
  value: "sk-chatig"

# main server port
port: 8081

# database
database: "postgres://chatig:chatig@localhost/chatig"