# Used to set configurations for the system

# Used to store uploaded files
temp_docs_path: "/root/.chatig/data/temp_docs"

# admin password
apikey:
  value: "chatig"

# main server port
port: 8083

# database
database: "postgres://chatig:chatig@localhost/chatig"