refresh_rate: 30 seconds

appenders:
  access_console:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  access_file:
    kind: rolling_file
    path: "/var/log/chatig/access.log"
    encoder:
      pattern: "{l} - {m}{n}"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 gb
      roller:
        kind: fixed_window
        pattern: "/var/log/chatig/access.{}.log"
        count: 5

  error_console:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  error_file:
    kind: rolling_file
    path: "/var/log/chatig/error.log"
    encoder:
      pattern: "{l} - {m}{n}"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 gb
      roller:
        kind: fixed_window
        pattern: "/var/log/chatig/error.{}.log"
        count: 5

  token_console:
    kind: console
    encoder:
      pattern: "{l} - {m}{n}"

  token_file:
    kind: rolling_file
    path: "/var/log/chatig/token.log"
    encoder:
      pattern: "{m}{n}"
    append: true
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 gb
      roller:
        kind: fixed_window
        pattern: "/var/log/chatig/token.{}.log"
        count: 2
        base: 1

loggers:
  token:
    level: info
    appenders:
      # - token_console
      - token_file
  access_log:
    level: info
    appenders:
      - access_console
      - access_file
  error_log:
    level: error
    appenders:
      - error_console
      - error_file
