qwen_models:
  qwen_7b_chat:
    reqwest_url: "http://x.x.x.x:1025/v1/chat/completions"
    model_name: "Qwen-7B-Chat"
    max_tokens: 32768
  
  qwen2_5_7b_instruct:
    reqwest_url: "http://x.x.x.x:8000/v1/chat/completions"
    model_name: "Qwen/Qwen2.5-7B-Instruct"
    max_tokens: 30000

glm_models:
  glm_7b_chat:
    reqwest_url: "http://x.x.x.x:30647/v1/chat/completions"
    model_name: "GLM-7B-Chat"
    max_tokens: 32768