# Use to configure the server address of the service

chatchat:
  # The IP and port where the ChatChat model is deployed
  kb_chat: "http://x.x.x.x:30008/chat/kb_chat"
  upload_temp_docs: "http://x.x.x.x:30008/knowledge_base/upload_temp_docs"
  file_chat: "http://x.x.x.x:30008/chat/file_chat"
  completion: "http://x.x.x.x:30008/chat/chat/completions"

  # The model used by chatchat, for example: glm4-chat, qwen1.5-chat
  model_name: "glm4-chat"

euler_copilot:
  # The IP and port where the Copilot model is deployed
  get_answer: "http://x.x.x.x:32230/kb/get_answer"
  get_stream_answer: "http://x.x.x.x:32230/kb/get_stream_answer"

vllm:
  completion: "http://x.x.x.x:8000/v1/chat/completions"
  model_name: "Qwen/Qwen2.5-1.5B-Instruct"  # the model of vllm

mindie:
  completion: "http://x.x.x.x:1025/v1/chat/completions"
  model_name: "Qwen-7B-Chat"  # the model of mindie
